Repository brunohjs/rasa-model-report, pull requests merged in 2022-12, with the labels that each got.

#19 #16
  .gitignore
  CHANGELOG.md
  README.md
  setup.cfg
  src/rasa_model_report/controllers/nlu_controller.py
  src/rasa_model_report/helpers/utils.py
  src/rasa_model_report/main.py
  tests/test_nlu_controller.py
  tests/test_utils.py
Labels: bug

#21 17 - Fix image URL
  README.md
Labels: bug, documentation

#22 17 - Fix image URL
  README.md
Labels: bug, documentation

#23 #10
  CHANGELOG.md
  makefile
  scripts/release.py
  setup.py
Labels: config

#25 10 - Add version badge
  README.md
Labels: documentation

#27 10 - Fix CHANGELOG
  CHANGELOG.md
Labels: documentation

#28 10 - Fix on README
  README.md
Labels: bug, documentation

#35 30 - Added more badges to README.md
  CHANGELOG.md
  README.md
Labels: documentation

#36 32 - Fix error when install modules
  .github/workflows/test.yml
  README.md
  makefile
  requirements.txt
  setup.py
Labels: bug

#37 32 - Adjust on changelog
  CHANGELOG.md
Labels: documentation

#34 Issue 31 - Support for python version 3.8 or higher
  .gitignore
  CHANGELOG.md
  README.md
  docs/markdown/another_sample_model_report.md
  setup.cfg
  setup.py
  src/rasa_model_report/controllers/csv_controller.py
  src/rasa_model_report/controllers/json_controller.py
  src/rasa_model_report/controllers/markdown_controller.py
  src/rasa_model_report/controllers/model_report.py
  src/rasa_model_report/controllers/nlu_controller.py
  src/rasa_model_report/helpers/type_aliases.py
  src/rasa_model_report/helpers/utils.py
  src/rasa_model_report/main.py
  tests/conftest.py
  tests/test_csv_controller.py
  tests/test_json_controller.py
  tests/test_markdown_controller.py
  tests/test_model_report.py
  tests/test_nlu_controller.py
  tests/test_utils.py
Labels: feature

#39 #31 - Support for python version 3.8 or higher
  .github/workflows/test.yml
  .gitignore
  CHANGELOG.md
  README.md
  docs/markdown/another_sample_model_report.md
  setup.cfg
  setup.py
  src/rasa_model_report/controllers/csv_controller.py
  src/rasa_model_report/controllers/json_controller.py
  src/rasa_model_report/controllers/markdown_controller.py
  src/rasa_model_report/controllers/model_report.py
  src/rasa_model_report/controllers/nlu_controller.py
  src/rasa_model_report/helpers/type_aliases.py
  src/rasa_model_report/helpers/utils.py
  src/rasa_model_report/main.py
  tests/conftest.py
  tests/test_csv_controller.py
  tests/test_json_controller.py
  tests/test_markdown_controller.py
  tests/test_model_report.py
  tests/test_nlu_controller.py
  tests/test_utils.py
Labels: feature

#40 38 - Created --version CLI command
  CHANGELOG.md
  README.md
  src/rasa_model_report/controllers/json_controller.py
  src/rasa_model_report/controllers/markdown_controller.py
  src/rasa_model_report/controllers/nlu_controller.py
  src/rasa_model_report/helpers/type_aliases.py
  src/rasa_model_report/main.py
Labels: feature

#41 15 - Include rasa version param and rename project and version param
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  rasa_model_report/__init__.py
  rasa_model_report/controllers/__init__.py
  rasa_model_report/controllers/controller.py
  rasa_model_report/controllers/csv_controller.py
  rasa_model_report/controllers/json_controller.py
  rasa_model_report/controllers/markdown_controller.py
  rasa_model_report/controllers/model_report.py
  rasa_model_report/controllers/nlu_controller.py
  rasa_model_report/helpers/__init__.py
  rasa_model_report/helpers/type_aliases.py
  rasa_model_report/helpers/utils.py
  rasa_model_report/main.py
  setup.py
  src/rasa_model_report/helpers/__init__.py
  tests/conftest.py
  tests/test_controller.py
  tests/test_csv_controller.py
  tests/test_json_controller.py
  tests/test_markdown_controller.py
  tests/test_model_report.py
  tests/test_nlu_controller.py
Labels: documentation, feature, test

#44 #18 - Create repository social media preview
  CHANGELOG.md
  docs/image/logo_white_words.png
  docs/image/social_media_preview.png
Labels: documentation
